version: '3.8'

services:
#  nginx:
#    build: ./services/nginx
#    ports:
#      - "443:443"
#    depends_on:
#      - web-frontend

  web-backend:
    build: ./services/web_backend
    command: gunicorn --bind 0.0.0.0:5000 main:app
    env_file: .env
    volumes:
      - ./services/bot:/home/services/bot
      - ./services/models:/home/services/models
      - ./services/database:/home/services/database
    ports:
      - "5000:5000"
  web-frontend:
    build: ./services/web-frontend
    command: npm run serve
    volumes:
      - /etc/ssl/certs/dhparam.pem:/etc/nginx/ssl_certs/dhparam.pem:ro
      - /etc/letsencrypt/live/airticketsbot.ru/fullchain.pem:/etc/nginx/ssl_certs/fullchain.pem:ro
      - /etc/letsencrypt/live/airticketsbot.ru/privkey.pem:/etc/nginx/ssl_certs/privkey.pem:ro
      - ./services/web-frontend/:/app
    ports:
      - "8080:8080"

  bot:
    build: ./services/bot
    command: python3 main.py
    env_file: .env
    volumes:
      - ./services/:/home/services/

